#
# (C) COPYRIGHT 2010-2019 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#

ifdef CONFIG_MALI_PLATFORM_THIRDPARTY
obj-y += $(patsubst %.c,%.o,$(wildcard $(src)/*/mali_kbase_config_*.c))
else
# Recursively compile selected platform directory
platform_name := $(shell echo $(CONFIG_MALI_PLATFORM_NAME))
obj-y += $(platform_name)/
endif
